# Generated by Django 3.2.7 on 2021-09-28 22:43

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210928_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_tags', to='catalog.paintingdetailpage'),
        ),
    ]
